# Generated by Django 5.1.2 on 2024-11-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0010_remove_pedido_usuario_pedido_total_alter_mesa_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('bebidas', 'Bebidas'), ('postres', 'Postres'), ('platos', 'Platos')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
