# Generated by Django 5.1.2 on 2024-11-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0015_remove_pedido_usuario_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
