# Generated by Django 5.1.2 on 2024-12-01 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0015_remove_pedido_usuario_pedido_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='contraseña',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesa', to=settings.AUTH_USER_MODEL),
        ),
    ]
