# Generated by Django 5.1.2 on 2024-11-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0016_detallepedido_total_alter_detallepedido_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
