# Generated by Django 5.1.2 on 2024-11-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0017_pedido_eliminado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='en_historial',
            field=models.BooleanField(default=False),
        ),
    ]
