# Generated by Django 5.1.2 on 2024-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_pedidos', '0018_pedido_en_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='stock_actualizado',
            field=models.BooleanField(default=False),
        ),
    ]
